sonar.projectKey=auth-manager-ex
sonar.projectName=AuthManagerEx
sonar.projectVersion=0.2.0
sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarqube.hpopp.dev
sonar.coverageReportPaths=cover/sonar-coverage.xml
